version: "3.7"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  redis:
      image: redis:alpine
      container_name: redis
      ports:
        - 6379:6379

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229 #debug port
    volumes:
      - .:/usr/app
    links:
      - database_rentx
      - redis
    depends_on:
      - database_rentx
      - redis


volumes:
  pgdata:
    driver: local